ChampData/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	# /championdata
	url(r'^$', views.index, name="index"),
	# /championdata/Ahri/
	url(r'^(?P<champion>[a-z | A-Z | 0-9 | _]+)/$', views.detail, name='detail'),
	url(r'^(?P<champion1>[a-z | A-Z | 0-9 | _]+)/(?P<champion2>[a-z | A-Z | 0-9 | _]+)/$', views.compare, name='compare'),
	
]

LeagueHelper/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    url(r'^$', include('ChampData.urls'), name='home'),
    url(r'^championdata/', include('ChampData.urls', namespace="ChampData")),
    url(r'^about/', include('myInfo.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^info/', include('SummonerInfo.urls'))
]

SummonerInfo/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^(?P<summoner_name>[a-z | A-Z | 0-9 | _]+)/$', views.summoner_info, name='info')
	]

myInfo/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.about, name="about"),
	
]

ChampData/models.py
from django.db import models


# a model for each champion that includes a name and style
class Champion(models.Model):
	name    = models.CharField('name', max_length = 255)
	#style   = models.CharField('style', max_length = 255)
	hp      = models.DecimalField('health', default = 0, max_digits=6, decimal_places=3)
	hpPlus  = models.DecimalField('health per level', default = 0, max_digits=6, decimal_places=3)
	hp5     = models.DecimalField('health per 5', default = 0, max_digits=6, decimal_places=3)
	hp5Plus = models.DecimalField('health per 5 per level', default = 0, max_digits=6, decimal_places=3)
	mp      = models.DecimalField('mana', default = 0, max_digits=6, decimal_places=3)
	mpPlus  = models.DecimalField('mana per level', default = 0, max_digits=6, decimal_places=3)
	mp5     = models.DecimalField('mana per 5', default = 0, max_digits=6, decimal_places=3)
	mp5Plus = models.DecimalField('mana per 5 per level', default = 0, max_digits=6, decimal_places=3)
	ad      = models.DecimalField('attack damage', default = 0, max_digits=6, decimal_places=3)
	adPlus  = models.DecimalField('attack damage per level', default = 0, max_digits=6, decimal_places=3)
	aSpeed  = models.DecimalField('attack speed', default = 0, max_digits=6, decimal_places=3)
	asPlus  = models.DecimalField('attack speed per level', default = 0, max_digits=6, decimal_places=1) 
	ar      = models.DecimalField('armor', default = 0, max_digits=6, decimal_places=3)
	arPlus  = models.DecimalField('armor per level', default = 0, max_digits=6, decimal_places=3)
	mr      = models.DecimalField('magic resist', default = 0, max_digits=6, decimal_places=3)
	mrPlus  = models.DecimalField('magic resist per level', default = 0, max_digits=6, decimal_places=3)
	ms      = models.IntegerField('movement speed', default = 0)
	adRange = models.IntegerField('range', default = 0)



	def __str__(self):
		return "{}".format(self.name)	

SummonerInfo/models.py
from django.db import models

# Create your models here.
class Summoner(models.Model):
    summoner_name = models.CharField(max_length=50)
    team_3v3_tier = models.CharField(max_length=10)
    team_3v3_rank = models.CharField(max_length=3)
    team_5v5_tier = models.CharField(max_length=10)
    team_5v5_rank = models.CharField(max_length=3)
    solo_5v5_tier = models.CharField(max_length=10)
    solo_5v5_rank = models.CharField(max_length=3)

myInfo/models.py
from django.db import models

# Create your models here.

ChampData/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from ChampData.models import Champion

def index(request):
	champion_list = []
	for champ in Champion.objects.order_by('name'):
		if ' ' in champ.name:
			champion_list.append(champ.name.replace(' ', '_'))
		elif "'" in champ.name:
			champion_list.append(champ.name.replace("'", '_'))
		elif "." in champ.name:
			champion_list.append(champ.nam.replace(".", ''))
	 	else:
			champion_list.append(champ.name)

	#champion_list = Champion.objects.order_by('name')
	context = {'champion_list': champion_list}
	return render(request, 'ChampData/base.html', context)

def compare(request, champion1, champion2):
	format_champion1 = champion1[0].upper() + champion1[1:].lower()
	format_champion2 = champion2[0].upper() + champion2[1:].lower()
	champion1_requested = get_object_or_404(Champion, name=format_champion1)
	champion2_requested = get_object_or_404(Champion, name=format_champion2)
	difference = []	

	list1 = Champion.objects.values_list('hp', 'hpPlus', 'hp5', 'hp5Plus','mp', 'mpPlus', 'mp5', 'mp5Plus', 'ad', 'adPlus', 'aSpeed', 'asPlus', 'ar', 'arPlus', 'mr', 'mrPlus', 'ms', 'adRange').filter(name=format_champion1)
	list2 = Champion.objects.values_list('hp', 'hpPlus', 'hp5', 'hp5Plus','mp', 'mpPlus', 'mp5', 'mp5Plus', 'ad', 'adPlus', 'aSpeed', 'asPlus', 'ar', 'arPlus', 'mr', 'mrPlus', 'ms', 'adRange').filter(name=format_champion2)

	for i in xrange(len(list1[0])):
		#if isinstance(list1[i], (int, float, long, complex)):
		difference.append(float(list1[0][i]) - float(list2[0][i]))

	
	context = {'champion1': champion1_requested,
		   'champion2': champion2_requested,
		   'difference': difference}
        
	return render(request, 'ChampData/compare.html', context)

def detail(request, champion):
	format_champion = champion[0].upper() + champion[1:].lower()
	champion_requested = get_object_or_404(Champion, name=format_champion)
	image_url = "ChampData/images/" + champion_requested.name + "_OriginalLoading.jpg"

	context = {'image_url': image_url,
		   'champion_name': champion_requested.name,
		   'hp': champion_requested.hp,
		   'hpPlus': champion_requested.hpPlus,
		   'hp5': champion_requested.hp5,
		   'hp5Plus': champion_requested.hp5Plus,
		   'mp': champion_requested.mp,
		   'mpPlus': champion_requested.mpPlus,
		   'mp5': champion_requested.mp5,
		   'mp5Plus': champion_requested.mp5Plus,
		   'ad': champion_requested.ad,
		   'adPlus': champion_requested.adPlus,
		   'as': champion_requested.aSpeed,
		   'asPlus': champion_requested.asPlus,
		   'ar': champion_requested.ar,
		   'arPlus': champion_requested.arPlus,
		   'mr': champion_requested.mr,
		   'mrPlus': champion_requested.mrPlus,
		   'ms': champion_requested.ms,
		   'range': champion_requested.adRange
	}
	
	return render(request, 'ChampData/ChampDetails.html', context)

SummonerInfo/views.py
from django.shortcuts import render
import LoLAPI

# Create your views here.
def summoner_info(request, summoner_name):
    lol = LoLAPI.LoLAPI(api_key='7f057410-5d0b-4174-b2e4-ad93f77c18d6')

    summoner_level = lol.summoner_objects_by_name(summoner_name)[summoner_name.lower()]['summonerLevel']
    summoner_id = lol.summoner_objects_by_name(summoner_name)[summoner_name.lower()]['id']

    #ranked_stats_table = lol.ranked_stats_by_id(self.id)['champions']
    player_stats_table = lol.player_stats_by_id(summoner_id)['playerStatSummaries']
    #masteries = lol.mastery_pages_by_id(self.id)
    #runes = lol.rune_pages_by_id(self.id)
    league = lol.leagues_by_id(summoner_id)[unicode(str(summoner_id), "utf-8")][0]
    for person in league['entries']:
        if person['playerOrTeamName'].lower() == summoner_name.lower():
            personal_league_data = person
    rank = league['tier'] + ' ' + personal_league_data['division']

    coop_vs_ai_5x5 = player_stats_table[0]
    coop_vs_ai_3x3 = player_stats_table[1]
    ranked_team_3x3 = player_stats_table[2]
    ranked_team_5x5 = player_stats_table[3]
    unranked_3x3 = player_stats_table[4]
    counterpick = player_stats_table[5]
    odin_unranked = player_stats_table[6]
    CAP5x5 = player_stats_table[7]
    ARAM = player_stats_table[8]
    unranked_5x5 = player_stats_table[9]
    URF = player_stats_table[10]
    ranked_solo_5x5 = player_stats_table[11]



    context = {'summoner_name': summoner_name,
               'summoner_id': summoner_id,
               'rank': rank,
               'coop_vs_ai_5x5': coop_vs_ai_5x5,
               'coop_vs_ai_3x3': coop_vs_ai_3x3,
               'ranked_team_3x3': ranked_team_3x3,
               'ranked_team_5x5': ranked_team_5x5,
               'unranked_3x3': unranked_3x3,
               'counterpick': counterpick,
               'odin_unranked': odin_unranked,
               'CAP5x5': CAP5x5,
               'ARAM': ARAM,
               'unranked_5x5': unranked_5x5,
               'URF': URF,
               'ranked_solo_5x5': ranked_solo_5x5,
               }
    return render(request, 'SummonerInfo/info.html', context)

myInfo/views.py
from django.shortcuts import render

def about(request):
	return render(request, 'myInfo/about.html')

ChampData/templates/ChampData/ChampDetails.html
{% extends 'ChampData/theme.html' %}
{% load staticfiles %}
{% block container %}
      <h1 style="text-align: center;">Champion Details</h1>
      <img style="float: left;" src="{% static image_url %}"/>
        {% if champion_name %}
          <table class="table table-hover">
            <tr><th><h4>Name:</h4></th><td><h4>{{ champion_name }}</h4></td></tr>
            <tr><th><h4>Health:</h4></th><td><h4>{{ hp }}</h4></td></tr>
            <tr><th><h4>Health per level:</h4></th><td><h4>{{ hpPlus }}</h4></td></tr>
            <tr><th><h4>Health Regen per 5:</h4></th><td><h4>{{ hp5 }}</h4></td></tr>
            <tr><th><h4>Health Regen per 5 per level:</h4></th><td><h4>{{ hp5Plus }}</h4></td></tr>
            <tr><th><h4>Mana:</h4></th><td><h4>{{ mp }}</h4></td></tr>
            <tr><th><h4>Mana per level:</h4></th><td><h4>{{ mpPlus }}</h4></td></tr>
            <tr><th><h4>Mana regen per 5:</h4></th><td><h4>{{ mp5 }}</h4></td></tr>
            <tr><th><h4>Mana regen per 5 per level:</h4></th><td><h4>{{ mp5Plus }}</h4></td></tr>
            <tr><th><h4>Attack Damage:</h4></th> <td><h4>{{ ad }}</h4></td></tr>
            <tr><th><h4>Attack Damage per level:</h4></th><td><h4>{{ adPlus }}</h4></td></tr>
            <tr><th><h4>Attack Speed:</h4></th> <td><h4>{{ as }}</h4></td></tr>
            <tr><th><h4>Attack Speed per level:</h4></th> <td><h4>{{ asPlus }}</h4></td></tr>
            <tr><th><h4>Armor:</h4></th> <td><h4>{{ ar }}</h4></td></tr>
            <tr><th><h4>Armor per level:</h4></th> <td><h4>{{ arPlus }}</h4></td></tr>
            <tr><th><h4>Magic Resist:</h4></th> <td><h4>{{ mr }}</h4></td></tr>
            <tr><th><h4>Magic Resist per level:</h4></th> <td><h4>{{ mrPlus }}</h4></td></tr>
            <tr><th><h4>Movement Speed:</h4></th> <td><h4>{{ ms }}</h4></td></tr>
            <tr><th><h4>Attack Range:</h4></th> <td><h4>{{ range }}</h4></td></tr>
          </table>
        {% endif %}
{% endblock %}

ChampData/templates/ChampData/about.html
{% extends 'ChampData/theme.html' %}

{% block title %}
	<title>About</title>
{% endblock %}

{% block container %}
	<h1>About page</h1>
{% endblock %}

ChampData/templates/ChampData/base.html
{% extends 'ChampData/theme.html' %}

{% block container %}
      <h1 style="text-align: center;">List of Champions</h1>
        {% if champion_list %}
          <ul>
            {% for champion_name in champion_list %}	
              <li style="display: inline;"><b><a href="{% url 'ChampData:detail' champion_name %}">{{ champion_name }}</a> | </b></li>
            {% endfor %}
          </ul>
        {% else %}
          <p>No Champions in list</p>
        {% endif %}
{% endblock %}

ChampData/templates/ChampData/compare.html
{% extends 'ChampData/theme.html' %}

{% block container %}
      <h1 style="text-align: center;">Champion Comparison</h1>
        {% if champion1 %}
	 {% if champion2 %}
          <table class="table table-hover">
           <tr><th><h4>Name:</h4></th>
		<td><h4><h4>{{ champion1.name }}</h4></td>
		<td><h4>{{ champion2.name }}</h4></td></tr>
            <tr><th><h4>Health:</h4></th>
		<td><h4>{{ champion1.hp }}</h4></td>
		<td><h4>{{ champion2.hp }}</h4></td>
		{% if difference.0 < 0 %}
			<td><h4><b style="color: red;">{{ difference.0 }}</b></h4></td></tr>
		{% else %}
			<td><h4><b style="color: green;">{{ difference.0 }}</b></h4></td></tr>
		{% endif %}
            <tr><th><h4>Health per level:</h4></th>
		<td><h4>{{ champion1.hpPlus }}</h4></td>
		<td><h4>{{ champion2.hpPlus }}</h4></td>
		{% if difference.1 < 0 %}
                        <td><h4><b style="color: red;">{{ difference.1 }}</b></h4></td></tr>
                {% else %}
                        <td><h4><b style="color: green;">{{ difference.1 }}</b></h4></td></tr>
                {% endif %}
            <tr><th><h4>Health Regen per 5:</h4></th>
		<td><h4>{{ champion1.hp5 }}</h4></td>
		<td><h4>{{ champion2.hp5 }}</h4></td>
		{% if difference.2 < 0 %}
                        <td><h4><b style="color: red;">{{ difference.2 }}</b></h4></td></tr>
                {% else %}
                        <td><h4><b style="color: green;">{{ difference.2 }}</b></h4></td></tr>
                {% endif %}
            <tr><th><h4>Health Regen per 5 per level:</h4></th>
		<td><h4>{{ champion1.hp5Plus }}</h4></td>
		<td><h4>{{ champion2.hp5Plus}}</h4></td>
		{% if difference.3 < 0 %}
                        <td><h4><b style="color: red;">{{ difference.3 }}</b></h4></td></tr>
                {% else %}
                        <td><h4><b style="color: green;">{{ difference.3 }}</b></h4></td></tr>
                {% endif %}
            <tr><th><h4>Mana:</h4></th>
		<td><h4>{{ champion1.mp }}</h4></td>
		<td><h4>{{ champion2.mp }}</h4></td>
		{% if difference.4 < 0 %}
                        <td><h4><b style="color: red;">{{ difference.4 }}</b></h4></td></tr>
                {% else %}
                        <td><h4><b style="color: green;">+{{ difference.4 }}</b></h4></td></tr>
                {% endif %}
            <tr><th><h4>Mana per level:</h4></th>
		<td><h4>{{ champion1.mpPlus }}</h4></td>
		<td><h4>{{ champion2.mpPlus }}</h4></td>
		{% if difference.5 < 0 %}
                        <td><h4><b style="color: red;">{{ difference.5 }}</b></h4></td></tr>
                {% else %}
                        <td><h4><b style="color: green;">{{ difference.5 }}</b></h4></td></tr>
                {% endif %}
            <tr><th><h4>Mana regen per 5:</h4></th>
		<td><h4>{{ champion1.mp5 }}</h4></td>
		<td><h4>{{ champion2.mp5 }}</h4></td>
		{% if difference.6 < 0 %}
                        <td><h4><b style="color: red;">{{ difference.6 }}</b></h4></td></tr>
                {% else %}
                        <td><h4><b style="color: green;">{{ difference.6 }}</b></h4></td></tr>
                {% endif %}
            <tr><th><h4>Mana regen per 5 per level:</h4></th>
		<td><h4>{{ champion1.mp5Plus }}</h4></td>
		<td><h4>{{ champion2.mp5Plus }}</h4></td>
		{% if difference.7 < 0 %}
                        <td><h4><b style="color: red;">{{ difference.7 }}</b></h4></td></tr>
                {% else %}
                        <td><h4><b style="color: green;">{{ difference.7 }}</b></h4></td></tr>
                {% endif %}
            <tr><th><h4>Attack Damage:</h4></th>
		<td><h4>{{ champion1.ad }}</h4></td>
		<td><h4>{{ champion2.ad }}</h4></td>
		{% if difference.8 < 0 %}
                        <td><h4><b style="color: red;">{{ difference.8 }}</b></h4></td></tr>
                {% else %}
                        <td><h4><b style="color: green;">{{ difference.8 }}</b></h4></td></tr>
                {% endif %}
            <tr><th><h4>Attack Damage per level:</h4></th>
		<td><h4>{{ champion1.adPlus }}</h4></td>
		<td><h4>{{ champion2.adPlus }}</h4></td>
		{% if difference.9 < 0 %}
                        <td><h4><b style="color: red;">{{ difference.9 }}</b></h4></td></tr>
                {% else %}
                        <td><h4><b style="color: green;">{{ difference.9 }}</b></h4></td></tr>
                {% endif %}
            <tr><th><h4>Attack Speed:</h4></th>
		<td><h4>{{ champion1.aSpeed }}</h4></td>
		<td><h4>{{ champion2.aSpeed }}</h4></td>
		{% if difference.10 < 0 %}
                        <td><h4><b style="color: red;">{{ difference.10 }}</b></h4></td></tr>
                {% else %}
                        <td><h4><b style="color: green;">{{ difference.10 }}</b></h4></td></tr>
                {% endif %}
            <tr><th><h4>Attack Speed per level:</h4></th>
		<td><h4>{{ champion1.asPlus }}</h4></td>
		<td><h4>{{ champion2.asPlus }}</h4></td>
		{% if difference.11 < 0 %}
                        <td><h4><b style="color: red;">{{ difference.11 }}</b></h4></td></tr>
                {% else %}
                        <td><h4><b style="color: green;">{{ difference.11 }}</b></h4></td></tr>
                {% endif %}
            <tr><th><h4>Armor:</h4></th>
		<td><h4>{{ champion1.ar }}</h4></td>
		<td><h4>{{ champion2.ar }}</h4></td>
		{% if difference.12 < 0 %}
                        <td><h4><b style="color: red;">{{ difference.12 }}</b></h4></td></tr>
                {% else %}
                        <td><h4><b style="color: green;">{{ difference.12 }}</b></h4></td></tr>
                {% endif %}
            <tr><th><h4>Armor per level:</h4></th>
		<td><h4>{{ champion1.arPlus }}</h4></td>
		<td><h4>{{ champion2.arPlus }}</h4></td>
		{% if difference.13 < 0 %}
                        <td><h4><b style="color: red;">{{ difference.13 }}</b></h4></td></tr>
                {% else %}
                        <td><h4><b style="color: green;">{{ difference.13 }}</b></h4></td></tr>
                {% endif %}
            <tr><th><h4>Magic Resist:</h4></th>
		<td><h4>{{ champion1.mr }}</h4></td>
		<td><h4>{{ champion2.mr }}</h4></td>
		{% if difference.14 < 0 %}
                        <td><h4><b style="color: red;">{{ difference.14 }}</b></h4></td></tr>
                {% else %}
                        <td><h4><b style="color: green;">{{ difference.14 }}</b></h4></td></tr>
                {% endif %}
            <tr><th><h4>Magic Resist per level:</h4></th>
		<td><h4>{{ champion1.mrPlus }}</h4></td>
		<td><h4>{{ champion2.mrPlus }}</h4></td>
		{% if difference.15 < 0 %}
                        <td><h4><b style="color: red;">{{ difference.15 }}</b></h4></td></tr>
                {% else %}
                        <td><h4><b style="color: green;">{{ difference.15 }}</b></h4></td></tr>
                {% endif %}
            <tr><th><h4>Movement Speed:</h4></th>
		<td><h4>{{ champion1.ms }}</h4></td>
		<td><h4>{{ champion2.ms }}</h4></td>
		{% if difference.16 < 0 %}
                        <td><h4><b style="color: red;">{{ difference.16 }}</b></h4></td></tr>
                {% else %}
                        <td><h4><b style="color: green;">{{ difference.16 }}</b></h4></td></tr>
                {% endif %}
            <tr><th><h4>Attack Range:</h4></th>
		<td><h4>{{ champion1.adRange }}</h4></td>
		<td><h4>{{ champion2.adRange }}</h4></td>
		{% if difference.17 < 0 %}
                        <td><h4><b style="color: red;">{{ difference.17 }}</b></h4></td></tr>
                {% else %}
                        <td><h4><b style="color: green;">{{ difference.17 }}</b></h4></td></tr>
                {% endif %}
          </table>
        {% endif %}
      {% endif %}
{% endblock %}
	

ChampData/templates/ChampData/comparewithjs.html
{% extends 'ChampData/theme.html' %}

{% block container %}
      <h1 style="text-align: center;">Champion Comparison</h1>
        {% if champion1 %}
	 {% if champion2 %}
          <table id="comparison_table" class="table table-hover">
            <script type="text/javascript">
            output = "<tr><th><h4>Name:</h4></th>
        <td><h4><h4>{{ champion1.name }}</h4></td>
        <td><h4>{{ champion2.name }}</h4></td></tr>
            <tr><th><h4>Style:</h4></th>
        <td><h4>{{ champion1.style }}</h4></td>
        <td><h4>{{ champion2.style }}</h4></td></tr>";

fields = ['hp', 'hpPlus', 'hp5', 'hp5Plus','mp', 'mpPlus', 'mp5', 'mp5Plus', 'ad', 'adPlus', 'aSpeed', 'asPlus', 'ar', 'arPlus', 'mr', 'mrPlus', 'ms', 'adRange'];
headers = ['Name', 'Style', 'Health', 'Health per level', 'Health Regen per 5', 'Mana', 'Mana per level', 'Mana regen per 5', 'Mana regen per 5 per level', 'Attack Damage', 'Attack Damage per level', 'Attack Speed', 'Attack Speed per level', 'Armor', 'Armor per level', 'Magic Resist', 'Magic Resist per level', 'Movement Speed', 'Attack Range'];
for (i = 0; i < 18; i++)
{
    output += "<tr><th><h4>" + headers[i+2] + ":</h4></th><td><h4>{{ champion1." + fields[i] + "}}</h4></td><td><h4>{{ " + "champion2." + fields[i] + " }}</h4></td>{% if difference." + i + " < 0 %}<td><h4><b style=\"color: red;\">{{ difference." + i + " }}</b></h4></td></tr>{% else %}<td><h4><b style=\"color: green;\">{{ difference." + i + " }}</b></h4></td></tr>{% endif %}";
}

document.getElementById("comparison_table").innerHTML = output;
</script>
          </table>
        {% endif %}
      {% endif %}
{% endblock %}
	

ChampData/templates/ChampData/theme.html
<!DOCTYPE html>

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'ChampData/css/bootstrap.min.css' %}" />

<html>
<head>
    <title>{% block title %}{{ champion_name }} Champion Data{% endblock %}</title>
</head>

<body style="padding-top: 50px;">

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand" href="#">LeagueLookup</a>
        </div> <!-- navbar-header -->

        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">ChampData</a></li>
            <li><a href="/about/">About</a></li>
            <li><a href="/contact/">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
        {% block container %}{% endblock %}
    </div><!-- /.container -->

  <!-- Bootstrap core JavaScript
    ================================================== -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="/static/bootstrap.min.js"></script>

</body>
</html>

SummonerInfo/templates/SummonerInfo/info.html
{% extends 'ChampData/theme.html' %}



{% block container %}
<style>
table, td, th {
  vertical-align: center;
  text-align: center;
}

</style>

	<h1>{{ summoner_name }}</h1>
	<h2>{{ summoner_id }}</h2>
	<h2>{{ rank }}</h2>

  <table class="table table-hover">
      <tr>
        <th>Queue</th>
        <th>Wins</th>
        <th>Losses</th>
      </tr>
      <tr>
        <td><p>Ranked Solo</p></td>
        <td><p>{{ ranked_solo_5x5.wins }}</p></td>
        <td><p>{{ ranked_solo_5x5.losses }}</p></td>
      </tr>
      <tr>
        <td><p>Normal</p></td>
        <td><p>{{ unranked_5x5.wins }}</p></td>
        <td><p>{{ unranked_5x5.aggregatedStats.totalSessionsLost }}</p></td>
      </tr> 
      <tr>
        <td><p>Normal 5v5</p></td>
        <td><p>{{ unranked_5x5.wins }}</p></td>
        <td><p>{{ unranked_5x5.aggregatedStats.totalSessionsLost }}</p></td>
      </tr>
      <tr>
        <td><p>ARAM</p></td>
        <td><p>{{ ARAM.wins }}</p></td>
        <td><p>{{ ARAM.aggregatedStats.totalSessionsLost }}</p></td>
      </tr>   
      <tr>
        <td><p>Normal 3v3</p></td>
        <td><p>{{ unranked_3x3.wins }}</p></td>
        <td><p>{{ unranked_3x3.aggregatedStats.totalSessionsLost }}</p></td>
      </tr>
      <tr>
        <td><p>Team Builder</p></td>
        <td><p>{{ CAP5x5.wins }}</p></td>
        <td><p>{{ CAP5x5.aggregatedStats.totalSessionsLost }}</p></td>
      </tr>
      <tr>
        <td><p>Ultra Rapid Fire</p></td>
        <td><p>{{ URF.wins }}</p></td>
        <td><p>{{ URF.aggregatedStats.totalSessionsLost }}</p></td>
      </tr>
      <tr>
        <td><p>Nemesis Draft</p></td>
        <td><p>{{ counterpick.wins }}</p></td>
        <td><p>{{ counterpick.aggregatedStats.totalSessionsLost }}</p></td>
      </tr>
      <tr>
        <td><p>Co-op vs AI 5v5</p></td>
        <td><p>{{ coop_vs_ai_5x5.wins }}</p></td>
        <td><p>{{ coop_vs_ai_5x5.aggregatedStats.totalSessionsLost }}</p></td>
      </tr>
      <tr>
        <td><p>Co-op vs. AI 3v3</p></td>
        <td><p>{{ coop_vs_ai_3x3.wins }}</p></td>
        <td><p>{{ coop_vs_ai_3x3.aggregatedStats.totalSessionsLost }}</p></td>
      </tr>
  </table>
{% endblock %}

myInfo/templates/myInfo/about.html
{% extends 'ChampData/theme.html' %}

{% block container %}
	<h1> new myInfo app</h1>
{% endblock %}

myInfo/templates/myInfo/contact.html
{% extends 'ChampData/theme.html' %}

{% block container %}
	<h1>contact page</h1>
{% endblock %}